# Generated by Django 6.0.3 on 2026-04-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Fundación', 'Fundación'), ('Junta de Vecinos', 'Junta de Vecinos'), ('Club Deportivo', 'Club Deportivo')], max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('contacto', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
